services:
- type: pserv
  # Using prebuilt image, so no repo or rootDir needed

  name: policy-boss-agent
  runtime: image

  # Free plan is not available for private services
  plan: starter

  # Docker image to use
  image:
    url: ghcr.io/sandeep-kumar-bigstep/policy-boss-livekit/policy-boss-agent:latest

  # Environment variables are stored in a group
  # created in the Render dashboard.
  envVars:
  - fromGroup: policy-boss-agent-env 
  region: singapore

  # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
  maxShutdownDelaySeconds: 300

  # Sane defaults
  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 80
    targetMemoryPercent: 80
version: "1"